import { createSupabaseClient } from "./supabase-client.js";
import { STOREFRONT_KEY, PAGE_SIZE } from "./config.js";
import { CATEGORY_HEROES } from "./category-heroes.js";
const supabase = await createSupabaseClient();
const params = new URLSearchParams(location.search);
const CATALOGUE_CATEGORIES=[["Cameras",726],["Lenses",731],["Drones",540],["Camera Accessories",405],["Video Cameras",293],["Lighting",199],["Action Cameras",182],["Video Production Equipment",156],["Audio",134],["Supports & Stabilisation",103],["Drone Accessories",65],["Power & Batteries",55],["Studio Equipment",11],["Other Equipment",33]];
const state={manufacturer:params.get("manufacturer")||"",category:params.get("category")||"",search:params.get("search")||"",offset:0,loading:false,finished:false,mode:(params.get("manufacturer")||params.get("category")||params.get("search"))?"products":"categories"};
const manufacturerSelect=document.querySelector("#manufacturer-select"),categorySelect=document.querySelector("#category-select"),searchInput=document.querySelector("#search-input"),productGrid=document.querySelector("#product-grid"),summary=document.querySelector("#result-summary"),loadMoreButton=document.querySelector("#load-more"),resultsEyebrow=document.querySelector("#results-eyebrow"),resultsTitle=document.querySelector("#results-title"),categoryHero=document.querySelector("#category-hero"),categoryHeroTitle=document.querySelector("#category-hero-title"),categoryHeroImage=document.querySelector("#category-hero-image"),categoryHeroDescription=document.querySelector("#category-hero-description");
function escapeHtml(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));}
function heroFor(c){return CATEGORY_HEROES[c]||null;}
function populateCategorySelect(){categorySelect.innerHTML='<option value="">All categories</option>'+CATALOGUE_CATEGORIES.map(([n])=>'<option value="'+escapeHtml(n)+'">'+escapeHtml(n)+'</option>').join("");categorySelect.value=state.category;}
async function loadManufacturers(){const {data,error}=await supabase.rpc("public_storefront_manufacturers",{p_store_key:STOREFRONT_KEY});if(error)throw error;for(const r of data.filter(r=>r.visible))manufacturerSelect.insertAdjacentHTML("beforeend",'<option value="'+escapeHtml(r.manufacturer)+'">'+escapeHtml(r.manufacturer)+' ('+r.product_count+')</option>');manufacturerSelect.value=state.manufacturer;}
function renderCategoryHero(){const h=heroFor(state.category);if(state.mode!=="products"||!h){categoryHero.hidden=true;return;}categoryHeroTitle.textContent=state.category;categoryHeroImage.src=h.image;categoryHeroImage.alt=h.alt;categoryHeroDescription.textContent=state.manufacturer?'Browse '+state.manufacturer+' products within '+state.category+'.':'Browse '+state.category+' from the connected catalogue.';categoryHero.hidden=false;}
function renderCategoryBrowser(){state.mode="categories";categoryHero.hidden=true;resultsEyebrow.textContent="ALL EQUIPMENT";resultsTitle.textContent="Browse catalogue";summary.textContent="Choose a category to start";loadMoreButton.hidden=true;productGrid.innerHTML=CATALOGUE_CATEGORIES.map(([c,count])=>{const h=heroFor(c),image=h?'<img src="'+escapeHtml(h.image)+'" alt="'+escapeHtml(h.alt)+'" loading="lazy">':'<div class="category-card-fallback">'+escapeHtml(c)+'</div>';return '<a class="product-card category-product-card" href="shop.html?category='+encodeURIComponent(c)+'"><div class="product-image category-product-image">'+image+'</div><div class="product-meta">CATEGORY</div><h2>'+escapeHtml(c)+'</h2><div class="product-meta">'+Number(count).toLocaleString()+' catalogue products</div><div class="availability available">Browse '+escapeHtml(c)+' <span>→</span></div></a>';}).join("");}
function imageKey(r){return[r.manufacturer,r.model,r.package_name,r.product_type,r.main_category||r.category].filter(Boolean).join(" ");}
function productImageUrl(r){return "https://commons.wikimedia.org/w/api.php?action=query&generator=search&gsrsearch="+encodeURIComponent(imageKey(r))+"&gsrnamespace=6&gsrlimit=1&prop=imageinfo&iiprop=url&iiurlwidth=900&format=json&origin=*";}
async function resolveImage(r,img){try{const j=await (await fetch(productImageUrl(r))).json(),p=Object.values(j?.query?.pages||{})[0],u=p?.imageinfo?.[0]?.thumburl||p?.imageinfo?.[0]?.url;if(u){img.src=u;img.alt=imageKey(r);img.hidden=false;img.closest(".product-image").classList.add("has-image");}}catch(e){console.warn("Product image lookup failed",imageKey(r));}}
function renderRows(rows,append){if(!append)productGrid.innerHTML="";const out=rows.map((r,i)=>{const id="catalogue-image-"+(state.offset+i),title=[r.manufacturer,r.model,r.package_name].filter(Boolean).join(" "),avail=Number(r.available_units||0);return '<article class="product-card" data-product="'+encodeURIComponent(JSON.stringify(r))+'"><div class="product-image"><div class="image-loading">Finding product image…</div><img id="'+id+'" hidden loading="lazy"></div><div class="product-meta">'+escapeHtml(r.main_category||r.category||"Catalogue")+'</div><h2>'+escapeHtml(title||"Unnamed product")+'</h2><div class="product-meta">'+escapeHtml(r.product_type||"")+'</div><div class="availability '+(avail>0?"available":"unavailable")+'">'+(avail>0?avail+' available for sale':"Catalogue item — availability pending")+'</div></article>';}).join("");productGrid.insertAdjacentHTML("beforeend",out);[...productGrid.querySelectorAll(".product-card")].slice(append?Math.max(0,productGrid.children.length-rows.length):0).forEach(card=>{const r=JSON.parse(decodeURIComponent(card.dataset.product)),img=card.querySelector("img");resolveImage(r,img).finally(()=>card.querySelector(".image-loading")?.remove());});}
async function loadProducts({append=false}={}){state.mode="products";if(state.loading||(state.finished&&append))return;state.loading=true;loadMoreButton.disabled=true;resultsEyebrow.textContent=state.category?"CATEGORY":"ALL EQUIPMENT";resultsTitle.textContent=state.category||"Browse catalogue";summary.textContent="Loading products…";const {data,error}=await supabase.rpc("public_storefront_catalog",{p_store_key:STOREFRONT_KEY,p_manufacturer:state.manufacturer||null,p_category:state.category||null,p_search:state.search||null,p_limit:PAGE_SIZE,p_offset:state.offset});state.loading=false;if(error){summary.textContent="Catalogue could not be loaded.";loadMoreButton.disabled=false;return;}renderCategoryHero();renderRows(data,append);state.offset+=data.length;state.finished=data.length<PAGE_SIZE;summary.textContent=state.offset.toLocaleString()+" products loaded";loadMoreButton.hidden=state.finished;loadMoreButton.disabled=false;}
function resetAndLoad(){state.offset=0;state.finished=false;state.mode="products";loadProducts();}
manufacturerSelect.addEventListener("change",()=>{state.manufacturer=manufacturerSelect.value;if(!state.manufacturer&&!state.category&&!state.search){renderCategoryBrowser();return;}resetAndLoad();});
categorySelect.addEventListener("change",()=>{state.category=categorySelect.value;if(!state.manufacturer&&!state.category&&!state.search){renderCategoryBrowser();return;}resetAndLoad();});
let timer;searchInput.addEventListener("input",()=>{clearTimeout(timer);timer=setTimeout(()=>{state.search=searchInput.value.trim();if(!state.manufacturer&&!state.category&&!state.search){renderCategoryBrowser();return;}resetAndLoad();},250);});
document.querySelector("#clear-filters").addEventListener("click",()=>{state.manufacturer="";state.category="";state.search="";state.offset=0;state.finished=false;manufacturerSelect.value="";categorySelect.value="";searchInput.value="";renderCategoryBrowser();});
loadMoreButton.addEventListener("click",()=>loadProducts({append:true}));
await loadManufacturers();populateCategorySelect();searchInput.value=state.search;if(state.mode==="categories")renderCategoryBrowser();else await loadProducts();